// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUrl = `-- name: AddUrl :exec
insert into url (key, url)
values ($1,$2)
`

type AddUrlParams struct {
	Key string
	Url pgtype.Text
}

func (q *Queries) AddUrl(ctx context.Context, arg AddUrlParams) error {
	_, err := q.db.Exec(ctx, addUrl, arg.Key, arg.Url)
	return err
}

const getUrl = `-- name: GetUrl :one
select key, url from url
where key = $1 limit 1
`

func (q *Queries) GetUrl(ctx context.Context, key string) (Url, error) {
	row := q.db.QueryRow(ctx, getUrl, key)
	var i Url
	err := row.Scan(&i.Key, &i.Url)
	return i, err
}
